[package]
name = "dot-generator"
version = "0.2.0"
edition = "2021"
license-file = "../LICENSE"
license = "MIT"
description = "the set of macros to generate dot files"

[dependencies]
dot-structures = { workspace = true }
